### ISSUE TITLE
0x66 is missing at the end of the vgm file

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/kss2vgm#1]
From the spec:
0x66 |   | end of sound data

Without it vgm_cmp (vgm compressor) won't work.

**Comment by okaxaki** [comment]
Hi, thank you for your information.
I will fix this issue asap!

**Comment by okaxaki** [comment]
I have fixed this problem at commit [94658e](https://github.com/digital-sound-antiques/kss2vgm/commit/94658e0893149c724b1d48c320bcdc9718116e63).
