### ISSUE TITLE
Header issues

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/kss2vgm#2]
```
printf "\x66" | cat quarth.vgm - > quarth2.vgm #Add 0x66 to the vgm, previous issue.
./vgm_ptch -Check quarth2.vgm # Check the resulting file, some minor issues.
VGM Patcher
-----------
File: quarth2.vgm ...
Check
Warning! EOF Offset before EOF command!
Wrong EOF Offset! (Header: 0x0493A3  File: 0x0493A4)
	   Header    Counted
Length	  2646000    2645701 !
Loop	        0          0
There are some errors. Press ESC / F (fix): F
File written.
```
vgm_ptch can fix the issues, but would be nice if it worked out of the box of course. :)

**Comment by okaxaki** [comment]
Hi,

This is not an independent issue. It seems that the printf command only added the 0x66 at the end of file but the  size value in the header was not modified. I also take care of this when I fix [issue #1](https://github.com/digital-sound-antiques/kss2vgm/issues/1). 
p.s. I modified your post with markdown code syntax.

**Comment by okaxaki** [comment]
Oops, I did not noticed the Length section! vgm_ptch seems to report 299 bytes shorter counter length than that in the header. This may be a bug of kss2vgm. I will investigate it.

**Comment by okaxaki** [comment]
I have fixed the missing 0x66 issue at commit [94658e](https://github.com/digital-sound-antiques/kss2vgm/commit/94658e0893149c724b1d48c320bcdc9718116e63) and this also solves this issue. Please open the issue again if vgm_ptch still reports error. Thanks.

**Comment by niekvlessert** [comment]
Tested; works fine. Thanks!!
