### ISSUE TITLE
The AY8910 frequency is off a bit

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/kss2vgm#3]
It should be 1789773 according to the VGM people.

**Comment by grauw** [comment]
That is 3579545.454545… / 2.

**Comment by okaxaki** [comment]
Hi, thank you for your report. I just copied the clock value 1789750 from the original [vgmspec171.txt](https://github.com/vgmrips/vgmplay/blob/master/VGMPlay/vgmspec171.txt)
I'll change AY8910 (and SCC) clock to 1789773 if the official vgmplay accepts the accurate clock.

**Comment by grauw** [comment]
Spec was updated,

**Comment by okaxaki** [comment]
Hi, I have just fixed the PSG and SCC clock value in the [repo](https://github.com/digital-sound-antiques/kss2vgm/commit/2f4f7bc65c2c8bfbf31d085fa3cc9c0704756530).
The binary release will be 0.1.1 milestone including the patch for  #4.
