### ISSUE TITLE
SCC+ music is saved as SCC music in the VGM

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/kss2vgm#4]
To select SCC+ bit 31 of the frequency should be set to 1. So the frequency should be 2149273421.

**Comment by okaxaki** [comment]
Hi, thank you for the information. I did not know that the vgm format supported SCC+!!
Is this an undocumented extension of the current vgm?

**Comment by okaxaki** [comment]
The vgmspec171.txt may be not updated for a year. 
I found the commit that SCC+ was supported at Jun 2016 in the VGMPlay repo.
https://github.com/vgmrips/vgmplay/commit/1572e68d73e6e877880719d0ee828afa9a2bcc7e#diff-94b442460b1342914b6b6853215a27c5

**Comment by niekvlessert** [comment]
It's currently undocumented indeed, the player and the vgm tools support it however.

**Comment by okaxaki** [comment]
I've patched the [source code](https://github.com/digital-sound-antiques/kss2vgm/commit/095c84a67fb9feb4c1b88342e3a3e55e2b22bcdb).

Unfortunately I currently need to prepare a build environment for windows.
Please be patient for a while if you need the binary release.
