### ISSUE TITLE
Exporting Y8950 KSS music with samplekit to VGM will loose the samples

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/kss2vgm#5]
For an example you can download http://www.worp3.com/download/msx_musics.rar. In it is KSS/theant/FLYBIJ.KSS. If I play it with for example Audio Overload it works just fine. However when I convert it to VGM the drums are gone. The drumkit is in the VGM file however, when playing it with vgmplay it quickly goes to 52% played, and vgm2txt shows me a lot of '1 samples (   0.02 ms)' and such in the beginning.

I've asked the VGM ppl, but it is possible I've been told.

If I can do anything to help, let me know.

**Comment by okaxaki** [comment]
Sorry that i did not mention it in the readme. The current implementation does not support Y8950 ADPCM samples.

**Comment by niekvlessert** [comment]
Ah, it's probably the same issue my OpenMSX vgm_rec script had, Grauw made a fix.

Check it out:
https://github.com/openMSX/openMSX/commit/871fc3275febc661cb0723daa51243059cfcccdc

**Comment by okaxaki** [comment]
Yes, kss2vgm still does not dump the ADPCM RAM. The code you mentioned is very helpful. Thank you!

**Comment by okaxaki** [comment]
Hi, I have written ADPCM support based on your pull request #6.
The code has been committed on develop branch at e4b349f66f79af5d18b7af8f351b977f6834963a

**Comment by okaxaki** [comment]
I noticed that the code above lacks some PCM durm sounds... Sorry, I will investigate it.

**Comment by okaxaki** [comment]
Hmmm, it seems that vgmplay does not load the ADPCM data that appears on early stage of the vgm data stream, if the pcm data block is not defined strictly at the top of the vgm commands. 
A light-weight workaround is to always generate a data block or, command-line option ...

**Comment by okaxaki** [comment]
I have solved the problem. All VGM commands are now written into the memory so that we can insert ADPCM data block for Y8950 into the top of the VGM stream after recording.
The code has been commited on kss2vgm/develop df3e33fcfff906f400b7899babc9e1bacfb97b32

**Comment by niekvlessert** [comment]
Amazing, I was thinking about in memory creation because it was the only nice way I could think of to be able to add the extra lines only when needed, but it would have taken me a lot of extra time to do it! I think it works fine, I'll test some more.
