### ISSUE TITLE
There is no sound in some channels of YM2413

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/kss2vgm#8]
The last three channels of the converted VGM have no sound, but the sound played in the OPX file is normal.
[OPLL vgm.zip](https://github.com/digital-sound-antiques/kss2vgm/files/6254692/OPLL.vgm.zip)

**Comment by denjhang** [comment]
[nrt002.zip](https://github.com/digital-sound-antiques/kss2vgm/files/6254705/nrt002.zip)

**Comment by okaxaki** [comment]
Which player do you use to play .vgm file?
These files use some trick to produce rhythm sound through the channel 7,8 and 9. It will not played correctly if you use the incomplete YM2413 emulator.

**Comment by denjhang** [comment]
I used the in vgm plug-in and tried other players with the same result

**Comment by denjhang** [comment]
ok....

**Comment by denjhang** [comment]
The newest vgmplay and in_vgm can be played normally it.
